/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        'on-background': '#2c3437',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d4dbdf',
        'surface-tint': '#4f4dcf',
        'surface-variant': '#dce4e8',
        'surface-container': '#eaeff2',
        'surface-container-low': '#f0f4f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e3e9ed',
        'surface-container-highest': '#dce4e8',
        'on-surface': '#2c3437',
        'on-surface-variant': '#596064',
        primary: '#4f4dcf',
        'primary-dim': '#423fc2',
        'primary-container': '#7777fa',
        'primary-fixed': '#7777fa',
        'primary-fixed-dim': '#6a69ec',
        'on-primary': '#fbf7ff',
        'on-primary-container': '#000000',
        'inverse-primary': '#8282ff',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        secondary: '#526074',
        'secondary-dim': '#465468',
        'secondary-container': '#d5e3fc',
        'on-secondary': '#f8f8ff',
        'on-secondary-container': '#455367',
        tertiary: '#755478',
        'tertiary-dim': '#68486c',
        'tertiary-container': '#fcd2fe',
        'on-tertiary': '#fff7fa',
        'on-tertiary-container': '#654569',
        error: '#a8364b',
        'error-dim': '#6b0221',
        'error-container': '#f97386',
        'on-error': '#fff7f7',
        'on-error-container': '#6e0523',
        outline: '#747c80',
        'outline-variant': '#acb3b7',
        dark: {
          background: '#0b0f10',
          surface: '#0b0f10',
          'surface-container-lowest': '#12181a',
          'surface-container-low': '#1a2124',
          'surface-container': '#232b2e',
          'surface-container-high': '#2c3437',
          'surface-container-highest': '#363f42',
          'on-surface': '#f7f9fb',
          'on-surface-variant': '#acb3b7',
        },
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        label: ['var(--font-body)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
      },
    },
  },
  plugins: [],
}
